force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Quiz-{0000}</displayFormat>
        <label>Quiz Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_1__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_1__c</fullName>
    <label>Answer: Option - 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_2__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_2__c</fullName>
    <label>Answer: Option - 2</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_3__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_3__c</fullName>
    <label>Answer: Option -3</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <label>Exam Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Ques_Set__c.field-meta.xml
<CustomField>
    <fullName>Ques_Set__c</fullName>
    <label>Ques - Set</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Set 4</fullName>
                <default>true</default>
                <label>Set 4</label>
            </value>
            <value>
                <fullName>Set 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/Quiz_Result__c.object-meta.xml
<CustomObject>
    <label>Quiz Result</label>
    <nameField>
        <displayFormat>QR - {0000}</displayFormat>
        <label>Quiz Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Result__c/fields/Exam_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Date_Time__c</fullName>
    <label>Exam Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <label>Exam Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Exam_Status__c.field-meta.xml
<CustomField>
    <fullName>Exam_Status__c</fullName>
    <label>Exam Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Exam_Taken_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Taken_Time__c</fullName>
    <label>Exam Taken Time</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Set_No__c.field-meta.xml
<CustomField>
    <fullName>Set_No__c</fullName>
    <label>Set No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Student_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Student_Attempts__c</fullName>
    <label>Student Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quiz_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Total_Questions__c.field-meta.xml
<CustomField>
    <fullName>Total_Questions__c</fullName>
    <label>Total Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Total_Time_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Time_Duration__c</fullName>
    <label>Total Time Duration</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/UAR_UUID__c.field-meta.xml
<CustomField>
    <fullName>UAR_UUID__c</fullName>
    <label>UAR-UUID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/user_attempt_result__c.object-meta.xml
<CustomObject>
    <label>User Attempt Result</label>
    <nameField>
        <displayFormat>UAN - {0000}</displayFormat>
        <label>User Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Attempt Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/user_attempt_result__c/fields/Attended_By__c.field-meta.xml
<CustomField>
    <fullName>Attended_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attended By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Attempt_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/IsCorrect_Answer__c.field-meta.xml
<CustomField>
    <fullName>IsCorrect_Answer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrect Answer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/Quiz_Question_Number__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Question_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quiz Question Number</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>User Attempt Results</relationshipLabel>
    <relationshipName>User_Attempt_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/Selected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Selected_Answer__c</fullName>
    <label>Selected Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/Selected_Question__c.field-meta.xml
<CustomField>
    <fullName>Selected_Question__c</fullName>
    <label>Selected Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/user_attempt_result__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountApiTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-29-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class AccountApiTest {
    @testSetup
    static void setup() {
        // Create Account and Contact
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Contact con = new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = acc.Id);
        insert con;

        // Create RecordType for Task
        // RecordType rt = new RecordType(
        //     Name = 'TestRT',
        //     SObjectType = 'Task',
        //     DeveloperName = 'TestRTDev'
        // );
        // insert rt;

        // Create Quiz__c
        Quiz__c quiz = new Quiz__c(
            isActive__c = true,
            Answer_Option_1__c = 'A',
            Answer_Option_2__c = 'B',
            Answer_Option_3__c = 'C',
            Correct_Answer__c = 'C',
            Ques_Set__c = 'Set 1',
            Exam_Name__c = 'Agentforce Specialist',
            Question__c = 'What is the answer?'
        );
        insert quiz;
	
        

        // Create a test User
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Student',
            LastName = 'User',
            Email = 'studentuser@test.com',
            Username = 'studentuser' + DateTime.now().getTime() + '@test.com',
            Alias = 'studusr',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = p.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
		Quiz_Result__c qr = new Quiz_Result__c();
        qr.Exam_Date_Time__c = system.now();
        qr.Exam_Name__c = 'AI';
        qr.Exam_Status__c = 'Pass';
        qr.Exam_Taken_Time__c = '08:13';
        qr.Percentage__c = 80.0;
        qr.Score__c = '37/40';
        qr.Set_No__c = 2;
        qr.Student_Attempts__c = 1;
        qr.Student_Name__c = testUser.Id;
        qr.Total_Questions__c = 5;
        qr.Total_Time_Duration__c = '01:01:47';
        qr.UAR_UUID__c = '123456';
        insert qr;
        // Create user_attempt_result__c
        user_attempt_result__c uar = new user_attempt_result__c(
            Selected_Question__c = quiz.Question__c,
            Selected_Answer__c = 'C',
            Correct_Answer__c = 'C',
            Quiz_Question_Number__c = quiz.Id,
            Attended_By__c = UserInfo.getUserId(),
            UUID__c = '123456',
            IsCorrect_Answer__c = true,
            Quiz_Result__c = qr.Id
        );
        insert uar;
        // Create Quiz_Result__c
        
		
    }

    @isTest
    static void testGetContactsByAccId() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        List<Contact> contacts = AccountApi.getContactsByAccId(acc.Id);
        System.assertEquals(1, contacts.size());
    }

    @isTest
    static void testGetAccounts() {
        List<Account> accounts = AccountApi.getAccounts();
        System.assert(accounts.size() > 0);
    }

    @isTest
    static void testGetQuestions() {
        List<Quiz__c> quizzes = AccountApi.getQuestions();
        System.assertEquals(1, quizzes.size());
    }

    @isTest
    static void testSaveQuizAnswers() {
        Quiz__c quiz = [SELECT Id, Question__c FROM Quiz__c LIMIT 1];
        
        
        Quiz_Result__c qr = new Quiz_Result__c();
        qr.Exam_Date_Time__c = system.now();
        qr.Exam_Name__c = 'AI';
        qr.Exam_Status__c = 'Pass';
        qr.Exam_Taken_Time__c = '08:13';
        qr.Percentage__c = 80.0;
        qr.Score__c = '37/40';
        qr.Set_No__c = 2;
        qr.Student_Attempts__c = 1;
        qr.Student_Name__c = UserInfo.getUserId();
        qr.Total_Questions__c = 5;
        qr.Total_Time_Duration__c = '01:01:47';
        qr.UAR_UUID__c = '123456';
        user_attempt_result__c uar = new user_attempt_result__c(
            Selected_Question__c = quiz.Question__c,
            Selected_Answer__c = 'C',
            Correct_Answer__c = 'C',
            Quiz_Question_Number__c = quiz.Id,
            Attended_By__c = UserInfo.getUserId(),
            UUID__c = '123456',
            IsCorrect_Answer__c = true,
            Quiz_Result__c = qr.Id
        );
        List<user_attempt_result__c> uarList = new List<user_attempt_result__c>{uar};
        List<Quiz_Result__c> qrList = new List<Quiz_Result__c>{qr};
        Test.startTest();
        String resultId = AccountApi.saveQuizAnswers(uarList, qrList);
        Test.stopTest();
        System.assertNotEquals(null, resultId);
    }

    @isTest
    static void testGetQuizResults() {
        List<Quiz_Result__c> results = AccountApi.getQuizResults();
        System.assert(results.size() > 0);
    }
}