force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Quiz-{0000}</displayFormat>
        <label>Quiz Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_1__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_1__c</fullName>
    <label>Answer: Option - 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_2__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_2__c</fullName>
    <label>Answer: Option - 2</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Answer_Option_3__c.field-meta.xml
<CustomField>
    <fullName>Answer_Option_3__c</fullName>
    <label>Answer: Option -3</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Ques_Set__c.field-meta.xml
<CustomField>
    <fullName>Ques_Set__c</fullName>
    <label>Ques - Set</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Set 4</fullName>
                <default>true</default>
                <label>Set 4</label>
            </value>
            <value>
                <fullName>Set 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_Subject_Per_Record_Type_Id__mdt/Task_Subject_Per_Record_Type_Id__mdt.object-meta.xml
<CustomObject>
    <label>Task Subject</label>
    <pluralLabel>Task Subjects</pluralLabel>
</CustomObject>

force-app/main/default/objects/Task_Subject_Per_Record_Type_Id__mdt/fields/Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Developer_Name__c</fullName>
    <label>Record Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Subject_Per_Record_Type_Id__mdt/fields/Subject_Value__c.field-meta.xml
<CustomField>
    <fullName>Subject_Value__c</fullName>
    <label>Subject Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/AccountApi_20250623040217.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-23-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AccountApi {
    public static List<Contact> getContactsByAccId(Id accId) {
        List<contact> conLists = [Select Id, FirstName, LastName From Contact where AccountId =:accId];
        return conLists;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts() {
        List<Account> accLists = [Select Id, Name From Account limit 100];
        return accLists;
    }
    
    // get account country state city data and display in LWC pages

   	@AuraEnabled(cacheable=true)
    public static List<String> getTaskSubjectsByRecordId() {
        Id recordTypeId = '012Qy000006ipY1IAI'; // example
        RecordType rt = [SELECT DeveloperName FROM RecordType WHERE Id = :recordTypeId LIMIT 1];
        String recordTypeDevName = rt.DeveloperName;
        system.debug('get rec type name: '+recordTypeDevName);
        List<String> subjectValues = new List<String>();
       
        // get custom meta data for filter
        List<String> subjects = new List<String>();

        for (Task_Subject_Per_Record_Type_Id__mdt mapping : [SELECT Subject_Value__c FROM Task_Subject_Per_Record_Type_Id__mdt WHERE Record_Type_Developer_Name__c = :recordTypeDevName AND Active__c = true order by Order__c]) {
            subjects.add(mapping.Subject_Value__c);
        }
        
        Schema.DescribeFieldResult fieldResult = Task.Subject.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
		system.debug('get picklistEntries: '+picklistEntries);
        List<String> finalSubjects = new List<String>();
        for (Schema.PicklistEntry entry : picklistEntries) {
            if (entry.isActive() && subjects.contains(entry.getLabel())) {
                finalSubjects.add(entry.getLabel());
            }
        }
        system.debug('get subjectValues: '+subjectValues);
        system.debug('get subjects from custome: '+subjects);
        system.debug('get finalSubjects: '+finalSubjects);
        return finalSubjects;
    }
    
    
    
    @AuraEnabled(cacheable=true)
    public static List<String> getTaskSubjects(Id recordTypeId) {
        List<String> subjectValues = new List<String>();
        // Get the Task.Subject field describe
        Schema.DescribeFieldResult fieldResult = Task.Subject.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();

        for (Schema.PicklistEntry entry : picklistEntries) {
            // Only include values valid for the given Record Type
            if (entry.isActive() && (entry.isDefaultValue())) {
                subjectValues.add(entry.getLabel());
            }
        }
        return subjectValues;
    }



    @AuraEnabled(cacheable=true)
    public static List<String> getTaskPriorities() {  
        return [SELECT Id, Answer_Option_1__c, Answer_Option_2__c, Answer_Option_3__c, Correct_Answer__c, Ques_Set__c , Question__c, Name FROM Quiz__c where Active__c = true]
            .stream()
            .map(q -> q.Answer_Option_1__c + ', ' + q.Answer_Option_2__c + ', ' + q.Answer_Option_3__c)
            .collect(Collectors.toList());
    }
}